CMS.Web/Controllers/FinancialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web2.Controllers
{
    public class FinancialController : Controller
    {
        // GET: Finance
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UpdateContribution()
        {
            return View();
        }

        public ActionResult CreateContribution()
        {
            return View();
        }

        public ActionResult CreateExpense()
        {
            return View();
        }

        public ActionResult Bank()
        {
            return View();
        }

        public ActionResult UpdateDeposit()
        {
            return View();
        }        

        public ActionResult Reimbursement()
        {
            return View();
        }
              
        public ActionResult UpsertBank()
        {
            return View();
        }

        public ActionResult BankTransfer()
        {
            return View();
        }
    }
}

CMS.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web2.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public ActionResult Pagination()
        {
            return View();
        }
    }
}

CMS.Web/Views/Shared/Pagination.cshtml
@{
    Layout = null;
}
<ul style="margin:0px" class="pagination" ng-if="1 < pages.length">
    <li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }">
        <a href="" ng-click="setCurrent(1)">First</a>
    </li>
    <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }" class="ng-scope">
        <a href="" ng-click="setCurrent(pagination.current - 1)" class="ng-binding">Previous</a>
    </li>
    <li ng-repeat="pageNumber in pages track by $index" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == '...' }">
        <a href="" ng-click="setCurrent(pageNumber)">{{ pageNumber }}</a>
    </li>
    <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }" class="ng-scope">
        <a href="" ng-click="setCurrent(pagination.current + 1)" class="ng-binding">Next</a>
    </li>
    <li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == pagination.last }">
        <a href="" ng-click="setCurrent(pagination.last)">Last</a>
    </li>
</ul>

CMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <style>
        html, body,#divBody, .splitterContainer > div{
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }
    </style>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

  
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" >
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Finance", "Index", "Financial")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div id="divBody" ng-app="APP" style="overflow:auto">
        <div style="height:calc(100% - 80px)">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>    
    @Scripts.Render("~/bundles/jquery") 
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/kendo")
    @RenderSection("MyScripts", required: false)
    @Scripts.Render("~/bundles/customDirectives")

</body>
</html>